import '@/app/ui/global.css'
import { robotoMono } from './ui/fonts'
import AppProvider from "./providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${robotoMono.className} antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}